spring.application.name=notification-lab

# postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.portfolio.notification-lab.domain
mybatis.configuration.map-underscore-to-camel-case=true

# logging
logging.level.portfolio.notification_lab=INFO
logging.level.org.mybatis=INFO

# notification worker
notification.worker.enabled=true
notification.worker.limit=1000
notification.worker.fixed-delay-ms=1000

# notification retry
notification.retry.next-retry-seconds=60
notification.retry.max-retry-count=3

# notification recovery
notification.recovery.enabled=false
notification.recovery.timeout-minutes=5
notification.recovery.fixed-delay-ms=60000
