spring.application.name=notification-lab

# postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.portfolio.notification-lab.domain
mybatis.configuration.map-underscore-to-camel-case=true

# logging
#logging.level.com.portfolio.notification-lab=DEBUG
logging.level.org.mybatis=DEBUG
